# Generated by Django 3.0.6 on 2020-06-10 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='blogapp/blog/images')),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('T', 'Technology'), ('E', 'Entertainment'), ('S', 'Sports'), ('P', 'Politics')], max_length=1)),
                ('views', models.IntegerField(default='0')),
            ],
        ),
    ]
