# Generated by Django 3.0.6 on 2020-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200610_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Politics', 'Politics')], max_length=20),
        ),
    ]
