# Generated by Django 3.0.6 on 2020-08-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='static/blogapp/images/logo.jpg', upload_to='blogapp/about/images'),
        ),
    ]
