# Generated by Django 3.0.6 on 2020-08-21 18:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0012_about_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorylist',
        ),
    ]
