# Generated by Django 3.0.6 on 2020-08-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_auto_20200822_0225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
