# Generated by Django 3.0.6 on 2020-08-21 20:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(default='static/blogapp/images/logo.jpg', upload_to='blogapp/about/images')),
            ],
        ),
    ]
