# Generated by Django 3.0.6 on 2020-08-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_title',
            new_name='title',
        ),
    ]
