# Generated by Django 3.0.6 on 2020-08-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_auto_20200822_0237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
